### PR TITLE
Bumpup version to 4.9.0

### PR DESCRIPTION
**Pull request by satsukies**
We will create a new release after this PR is merged.

### CODE REVIEW

**Comment by jmatsu** [comment]
@satsukies 
I'm sorry for missing points on your PR. SdkDeviceStatesCollector should be thread-safe for reading/writing attributes. This could be a release blocker.

https://github.com/DeployGate/deploygate-android-sdk/blob/7459c6668d892a1b9e08aa26de5652b30cedaee7/sdk/src/main/java/com/deploygate/sdk/SdkDeviceStatesCollector.java

**Comment by satsukies** [comment]
@jmatsu 
I fixed it on https://github.com/DeployGate/deploygate-android-sdk/pull/99 .
Please check and review it. Thanks.

**Comment by satsukies** [comment]
This PR was automatically closed unexpectedly :(
So I reopen this.

**Review by jmatsu — APPROVED** [review]
Good 🎉

**Comment by satsukies** [comment]
Thank you!

**Pull request merged**
